version: '2'

services:
  webapp:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - "/code/node_modules"
      - "/code/node_api/node_modules"
      - "/code/node_tools/node_modules"

  mysql:
    image: mysql:5.6.46
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

