version: '3.1'

services:
  webapp:
    image: lsby/nodejs
    ports:
      - "80:80"
    volumes:
      - ".:/root/pro"
      - "/root/run"
      - "/usr/local/lib/node_modules"
      - "/usr/local/bin"
    depends_on:
      - "mysql"
    links:
      - "mysql:mysqlhost"
    restart: always

  mysql:
    image: mysql:5.6
    ports:
      - "3306:3306"
    volumes:
      - "/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    restart: always

  adminer:
    image: adminer
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    restart: always
