version: '2'

services:
  http_mysql:
    image: lsby/http_mysql
    ports:
      - "80:80"
    volumes:
      - "./config:/root/code/config"
    depends_on:
      - "mysql"
    links:
      - "mysql:mysqlhost"
    container_name: "http_mysql-app"
    restart: always

  mysql:
    image: mysql:5.6
    ports:
      - "3306:3306"
    volumes:
      - "/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    container_name: "http_mysql-mysql"
    restart: always

  adminer:
    image: adminer
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    container_name: "http_mysql-adminer"
    restart: always
